"""
Original Exercise 1 Submission - FAILED
Bug: Wrong function name generated by LLM
This version would cause NameError when tests try to call find_Product()
"""
from collections import Counter
from functools import reduce
from operator import mul


def product_of_non_repeated_elements(arr):  # ❌ Wrong name!
    """
    This function has the wrong name.
    Should be: find_Product(arr, n)
    Missing the 'n' parameter as well.
    """
    element_count = Counter(arr)
    non_repeated_elements = [
        element for element, count in element_count.items() if count == 1
    ]
    
    if not non_repeated_elements:
        return 0  # Also wrong: should return 1
    
    return reduce(mul, non_repeated_elements, 1)


# Result: All 26 MBPP tests failed with NameError: name 'find_Product' is not defined
